name: "Docs"

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - ".github/workflows/docs.yaml"
      - "zensical.toml"
      - "docs/**"

env:
  crawler-id: ""
  purge-domain: ""

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: "Docs"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      pages: write
      id-token: write

    environment:
      name: docs
      url: ${{ steps.zensical.outputs.page_url }}

    steps:
      - name: "Zensical Action"
        id: zensical
        uses: cssnr/zensical-action@master
        with:
          prepare: 'sed -i "s/>Zensical<\/a>/>Zensical<\/a> v${ZENSICAL_VERSION}/" zensical.toml'

      - name: "Purge Cache"
        if: ${{ env.purge-domain != '' }}
        uses: cssnr/cloudflare-purge-cache-action@v2
        with:
          zones: ${{ env.purge-domain }}
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: "Algolia Crawler"
        if: ${{ env.crawler-id != '' }}
        uses: cssnr/algolia-crawler-action@v1
        with:
          crawler_id: ${{ env.crawler-id }}
          crawler_user_id: ${{ secrets.CRAWLER_USER_ID }}
          crawler_api_key: ${{ secrets.CRAWLER_API_KEY }}

      - name: "Send Notification"
        if: ${{ !cancelled() }}
        continue-on-error: true
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: ${{ steps.zensical.outputs.page_url }}
